### PR TITLE
Initial set of tools

### PR DESCRIPTION
**Pull request by supakeen**
DO NOT MERGE

# TODO

- [ ] Rebase on #2.

## Tools (incomplete list)

- [ ] [kiwi](https://github.com/OSInside/kiwi).
- [ ] [lorax](https://github.com/weldr/lorax), and mention `livemedia-creator` here as well.
- [ ] [packer](https://github.com/hashicorp/packer).
- [ ] [ubuntu-builder](https://launchpad.net/ubuntu-builder/+download).
- [ ] [mkosi](https://github.com/systemd/mkosi).
- [x] [osbuild](https://github.com/osbuild/osbuild)
- [x] [osbuild-composer](https://github.com/osbuild/osbuild-composer)
- [ ] podman
- [ ] docker
- [ ] [ImageFactory](https://github.com/redhat-imaging/imagefactory)
- [ ] [Oz](https://github.com/clalancette/oz)
- [ ] [isogenerator](https://github.com/ublue-os/isogenerator)

## Orchestrators

- [ ] koji.
- [ ] pungi.

## Services

- [ ] image-builder, the web service on console.redhat.com and console.stg.fedorainfracloud.org and its API.
- [ ] cockpit-composer, the web frontend for osbuild-composer in cockpit.

### CODE REVIEW

**Comment by schaefi** [comment]
I also know about

* ubuntu-builder: https://launchpad.net/ubuntu-builder/+download

**Comment by supakeen** [comment]
@schaefi Thanks, added it to the todo list.

**Comment by AlexBaranowski** [comment]
Howdy!

From my experience working on the EuroLinux distro I would like to add the following:

- livemedia-creator (part of lorax so I do not know if it's valid for this list)
- pungi/pungi-koji - uses lorax internally
- podman/docker - to build container images

I would also split the tools based on:

- What are the inputs (RPM repos/deb repos/ISOs etc)
- What are the outputs (ISO installation file, Live media, Virtual Machine, Container etc)

Best,
Alex

**Comment by Conan-Kudo** [comment]
Uhh, I didn't notice this PR already when I made #2 😅

**Comment by supakeen** [comment]
@Conan-Kudo yes but yours is a great start as far as format goes; can you mark it as ready for review so we can merge it and then base this one on top of it?

**Comment by supakeen** [comment]
> Howdy!
> 
> From my experience working on the EuroLinux distro I would like to add the following:
> 
>     * livemedia-creator (part of lorax so I do not know if it's valid for this list)
> 
>     * pungi/pungi-koji - uses lorax internally
> 
>     * podman/docker - to build container images
> 
> 
> I would also split the tools based on:
> 
>     * What are the inputs (RPM repos/deb repos/ISOs etc)
> 
>     * What are the outputs (ISO installation file, Live media, Virtual Machine, Container etc)
> 
> 
> Best, Alex

Thank you, as far as pungi/pungi-koji go and correct me if I'm wrong the koji plugins are wrappers around the other tooling in this list and pungi is what creates koji tasks to run those. If anything we should mention it in a separate section.

livemedia-creator is indeed commonly used from lorax, let's mention it under lorax.

podman/docker: yep, let's add those.

The split: yep, let's do that!

**Comment by Conan-Kudo** [comment]
Alright, #2 is merged, so you can rebase on top of it.

**Comment by Conan-Kudo** [comment]
Most of this is already now in the document. Separate PRs should be opened up to add others.

**Pull request closed without merging**
